title: 'Benjamin Swartz Hartmann'
description: "Sociologist studying racism/race, immigration, boundary processes, and political culture + computational sociology"
logo: 'https://hartmannbs.github.io/img/circle_headshot_small.png'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
